name: WarpPlugin
main: me.shanodis.WarpPlugin.Main
version: 1.3
commands:
  warp:
    description: Warps player to an indicated location.
  setwarp:
    description: Sets a new warp.
  warplist:
    description: Prints the list of warps.
  warpdel:
    description: Deletes an indicated warp.